[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lanisapi"
version = "0.1.0"
authors = [
    { name = "kurwjan" }
]
description = "A unofficial python api for Lanis"
keywords = [
    "Lanis",
    "SPH",
    "Schulportal Hessen",
    "Hessen",
    "API"
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: German"
]
dependencies = [
    "httpx",
    "selectolax",
]

[project.urls]
"Homepage" = "https://github.com/kurwjan/LanisAPI"
"Bug Tracker" = "https://github.com/kurwjan/LanisAPI/issues"
